import { Elysia } from "elysia";
import type { Ingredient } from "@pizzaconstructor/shared";

export const PIZZA_CONSTRUCTOR_INGREDIENTS: Ingredient[] = [
  // Sauces
  {
    id: "sauce-tomato",
    name: "San Marzano Tomato Sauce",
    category: "sauce",
    price: 1.5,
    weightG: 80,
    caloriesKcal: 45,
    allergens: [],
    colorHex: "#e74c3c",
    icon: "🍅",
  },
  {
    id: "sauce-creamy-garlic",
    name: "Creamy Garlic White Sauce",
    category: "sauce",
    price: 2.0,
    weightG: 80,
    caloriesKcal: 120,
    allergens: ["Lactose"],
    colorHex: "#f5f5dc",
    icon: "🧄",
  },
  {
    id: "sauce-pesto",
    name: "Genovese Basil Pesto",
    category: "sauce",
    price: 2.5,
    weightG: 70,
    caloriesKcal: 160,
    allergens: ["Lactose", "Nuts"],
    colorHex: "#27ae60",
    icon: "🌿",
  },
  {
    id: "sauce-bbq",
    name: "Smoky Sweet BBQ Sauce",
    category: "sauce",
    price: 1.8,
    weightG: 80,
    caloriesKcal: 95,
    allergens: [],
    colorHex: "#8e44ad",
    icon: "🍯",
  },

  // Cheeses
  {
    id: "cheese-mozzarella",
    name: "Fior di Latte Mozzarella",
    category: "cheese",
    price: 2.5,
    weightG: 120,
    caloriesKcal: 280,
    allergens: ["Lactose"],
    colorHex: "#f4f6f7",
    icon: "🧀",
  },
  {
    id: "cheese-gorgonzola",
    name: "Aged Gorgonzola Blue",
    category: "cheese",
    price: 3.0,
    weightG: 80,
    caloriesKcal: 240,
    allergens: ["Lactose"],
    colorHex: "#d5dbdb",
    icon: "🧀",
  },
  {
    id: "cheese-parmesan",
    name: "Shaved Parmigiano-Reggiano",
    category: "cheese",
    price: 2.8,
    weightG: 50,
    caloriesKcal: 190,
    allergens: ["Lactose"],
    colorHex: "#fdebd0",
    icon: "🧀",
  },
  {
    id: "cheese-vegan",
    name: "Artisanal Vegan Cashew Cheese",
    category: "cheese",
    price: 3.5,
    weightG: 100,
    caloriesKcal: 210,
    allergens: ["Nuts"],
    colorHex: "#f9e79f",
    icon: "🌱",
  },

  // Meats
  {
    id: "meat-pepperoni",
    name: "Spicy Italian Pepperoni",
    category: "meat",
    price: 2.8,
    weightG: 70,
    caloriesKcal: 220,
    allergens: [],
    colorHex: "#c0392b",
    icon: "🥓",
  },
  {
    id: "meat-prosciutto",
    name: "Prosciutto di Parma",
    category: "meat",
    price: 3.8,
    weightG: 60,
    caloriesKcal: 160,
    allergens: [],
    colorHex: "#e6b0aa",
    icon: "🍖",
  },
  {
    id: "meat-chicken",
    name: "Herb Grilled Chicken",
    category: "meat",
    price: 2.5,
    weightG: 90,
    caloriesKcal: 140,
    allergens: [],
    colorHex: "#d7bde2",
    icon: "🍗",
  },
  {
    id: "meat-bacon",
    name: "Crispy Smoked Bacon",
    category: "meat",
    price: 2.6,
    weightG: 60,
    caloriesKcal: 210,
    allergens: [],
    colorHex: "#922b21",
    icon: "🥓",
  },

  // Vegetables
  {
    id: "veg-mushrooms",
    name: "Fresh Cremini Mushrooms",
    category: "vegetable",
    price: 1.5,
    weightG: 60,
    caloriesKcal: 15,
    allergens: [],
    colorHex: "#aab7b8",
    icon: "🍄",
  },
  {
    id: "veg-peppers",
    name: "Roasted Sweet Bell Peppers",
    category: "vegetable",
    price: 1.4,
    weightG: 70,
    caloriesKcal: 20,
    allergens: [],
    colorHex: "#e67e22",
    icon: "🫑",
  },
  {
    id: "veg-olives",
    name: "Kalamata Black Olives",
    category: "vegetable",
    price: 1.6,
    weightG: 50,
    caloriesKcal: 60,
    allergens: [],
    colorHex: "#2c3e50",
    icon: "🫒",
  },
  {
    id: "veg-artichokes",
    name: "Marinated Artichoke Hearts",
    category: "vegetable",
    price: 2.2,
    weightG: 60,
    caloriesKcal: 35,
    allergens: [],
    colorHex: "#7dcea0",
    icon: "🥗",
  },
  {
    id: "veg-onions",
    name: "Caramelized Red Onions",
    category: "vegetable",
    price: 1.2,
    weightG: 50,
    caloriesKcal: 30,
    allergens: [],
    colorHex: "#7d3c98",
    icon: "🧅",
  },
  {
    id: "veg-spinach",
    name: "Baby Spinach Leaves",
    category: "vegetable",
    price: 1.3,
    weightG: 40,
    caloriesKcal: 10,
    allergens: [],
    colorHex: "#229954",
    icon: "🥬",
  },
];

const getIngredientsHandler = () => {
  const grouped = {
    sauce: PIZZA_CONSTRUCTOR_INGREDIENTS.filter((i) => i.category === "sauce"),
    cheese: PIZZA_CONSTRUCTOR_INGREDIENTS.filter((i) => i.category === "cheese"),
    meat: PIZZA_CONSTRUCTOR_INGREDIENTS.filter((i) => i.category === "meat"),
    vegetable: PIZZA_CONSTRUCTOR_INGREDIENTS.filter((i) => i.category === "vegetable"),
    extra: PIZZA_CONSTRUCTOR_INGREDIENTS.filter((i) => i.category === "extra"),
  };

  return {
    ingredients: PIZZA_CONSTRUCTOR_INGREDIENTS,
    grouped,
    total: PIZZA_CONSTRUCTOR_INGREDIENTS.length,
  };
};

const ingredientsSchema = {
  detail: {
    summary: "Get all customizable ingredients for interactive pizza constructor",
    tags: ["Constructor"],
  },
};

export const ingredientsRoutes = new Elysia({ prefix: "/ingredients" })
  .get("/", getIngredientsHandler, ingredientsSchema)
  .get("/index", getIngredientsHandler, ingredientsSchema);
